### PR TITLE
Added Ldap filter to options

### PR DESCRIPTION
**Pull request by MrMEEE**

### CODE REVIEW

**Comment by esaracco** [comment]
Hello Martin,

Thank you for this new PR! Have you tested it with you own wopits instance?

Could you please update the following files?
- `site-config.template.php`
- `/README.md`
- `app/ldap/README.md`

You should also update those ones:
- `app/class/Ldap.php::getUserData()`:

This part:
```php
$filter = '(&(objectClass='.WPT_LDAP_OBJECTCLASS.')'.
          '(uid:caseExactMatch:='.ldap_escape ($uid, '', LDAP_ESCAPE_FILTER).'))';
```
-  `app/deploy/deploy::_checkConfig()`:

Something like that (*not tested!*):

```diff
@@ -170,8 +170,9 @@
           $this->help ("Conf `ldap->binddn` is empty!");
         if (empty ($env['ldap']['bindpw']))
           $this->help ("Conf `ldap->bindpw` is empty!");
-        if (empty ($env['ldap']['objectclass']))
-          $this->help ("Conf `ldap->objectclass` is empty!");
+        if (empty ($env['ldap']['objectclass']) &&
+            empty ($env['ldap']['filter']))
+          $this->help ("Conf `ldap->objectclass` or `ldap->filter` is empty!");
         if (empty ($env['ldap']['basedn']))
           $this->help ("Conf `ldap->basedn` is empty!");
       }
```

**Comment by MrMEEE** [comment]
Ok.. I will look in this, and add the above..

Just one question, when I try to authenticate with ldap.. I get a Protocol Error.. This is caused by using "caseExactMatch", but works fine if I do a manual lookup with ldapsearch it works fine?.. so seems like caseExactMatch is broken by php-ldap (maybe only some versions?)

Which PHP version have you tested with ldap integration?

**Comment by esaracco** [comment]
> Just one question, when I try to authenticate with ldap.. I get a Protocol Error.. This is caused by using "caseExactMatch", but works fine if I do a manual lookup with ldapsearch it works fine?.. so seems like caseExactMatch is broken by php-ldap (maybe only some versions?)
> 
> Which PHP version have you tested with ldap integration?

GNU/Linux Debian Buster. PHP v7.3.31.
No problem here.

**Comment by MrMEEE** [comment]
Hmmm.. I have the problem on both RHEL8 and Ubuntu.. but might be related to the FreeIPA server we are using.. The weird thing is that this only happens through php-ldap, and not other clients.. 

I think I'll create a feature to enable/disable the caseExactMatch, hope you'll accept it... will submit as a separate PR

**Comment by MrMEEE** [comment]
Hi

I have now added the additional information and code..

I don't believe that anything is needed in app/deploy/deploy::_checkConfig(), as this is not a required option..(fallback to objectclass)

**Pull request merged**
